server:
  port: 8080

spring:
  application:
    name: LibraryManagement


  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: sandy
    password: S@ndy2183
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: MyPostgresHikariPool
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      leak-detection-threshold: 60000

    jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      database-platform: org.hibernate.dialect.PostgresSQLDialect

    spring:
      liquibase:
        change-log: classpath:db/changelog/db.changelog-master.yaml




        org:
          springframework:
            security: ERROR

#    h2:
#      console:
#        enable: true
#        path: /h2-console
#

logging:
  level:
    root: INFO
    com.LibraryApi: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    org:
      springframework:
        security:
          web:
            access:
              ExceptionTranslationFilter: OFF